const DB='itKnowledgeBaseDB',VER=1,RS='records',MS='meta';
const CATS=['Office','Windows','硬體','網路','印表機','NAS','影音設備','Google Apps Script','GitHub','其他'];
const ICONS={'Office':'📊','Windows':'🪟','硬體':'🖥️','網路':'🌐','印表機':'🖨️','NAS':'💾','影音設備':'🎚️','Google Apps Script':'⚙️','GitHub':'🐙','其他':'📌'};
let db,records=[],cats=[],icons={},sync={url:'',key:'',autoSync:false},editId=null,detailId=null,attachments=[];
let view=localStorage.getItem('itkb_viewMode')||'cards';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const dateNow=()=>{let d=new Date();return[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const cloudPlaceholder='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="480"><rect width="100%" height="100%" fill="#f6f8fb"/><text x="50%" y="45%" text-anchor="middle" font-size="64">☁️</text><text x="50%" y="58%" text-anchor="middle" font-family="sans-serif" font-size="24" fill="#64748b">從 Google Drive 載入中…</text></svg>`);
function toast(x){let e=$('#toast');e.textContent=x;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2400)}
function modal(id,on=true){$('#'+id).classList.toggle('show',on)}
function openDB(){return new Promise((ok,no)=>{let q=indexedDB.open(DB,VER);q.onupgradeneeded=e=>{let d=e.target.result;if(!d.objectStoreNames.contains(RS))d.createObjectStore(RS,{keyPath:'id'});if(!d.objectStoreNames.contains(MS))d.createObjectStore(MS,{keyPath:'key'})};q.onsuccess=e=>{db=e.target.result;ok()};q.onerror=()=>no(q.error)})}
function req(store,mode,fn){return new Promise((ok,no)=>{let r=fn(db.transaction(store,mode).objectStore(store));r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
const all=s=>req(s,'readonly',o=>o.getAll()),put=(s,v)=>req(s,'readwrite',o=>o.put(v)),del=(s,k)=>req(s,'readwrite',o=>o.delete(k)),clear=s=>req(s,'readwrite',o=>o.clear());
const saveCats=()=>put(MS,{key:'categories',value:cats}),saveIcons=()=>put(MS,{key:'categoryIcons',value:icons}),saveSync=()=>put(MS,{key:'syncConfig',value:sync});
const icon=c=>icons[c]||'📌';
async function load(){records=await all(RS);let m=await all(MS),c=m.find(x=>x.key==='categories'),i=m.find(x=>x.key==='categoryIcons'),s=m.find(x=>x.key==='syncConfig');cats=c?.value?.length?c.value:[...CATS];icons={...ICONS,...(i?.value||{})};sync={...sync,...(s?.value||{})};if(!c)await saveCats();if(!i)await saveIcons();catUI();applyView();syncStatus();render()}
function applyView(){let list=view==='list';$('#records').classList.toggle('list',list);$('#viewCards').classList.toggle('active',!list);$('#viewList').classList.toggle('active',list)}
function syncStatus(t){let e=$('#syncStatus');if(t){e.textContent=t;return}let on=!!(sync.url&&sync.key);e.classList.toggle('on',on);e.textContent=on?'☁️ 試算表 + Drive 已設定':'☁️ 尚未設定雲端'}
function catUI(){let f=$('#categoryFilter'),v=f.value;f.innerHTML='<option value="">全部分類</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');f.value=cats.includes(v)?v:'';let s=$('#fCategory'),sv=s.value;s.innerHTML=cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(cats.includes(sv))s.value=sv;catList();$('#statCategories').textContent=cats.length}
function catList(){let use={};records.forEach(r=>use[r.category]=(use[r.category]||0)+1);$('#categoryList').innerHTML=cats.map(c=>`<div class="category-item"><input class="icon-input" value="${esc(icon(c))}" maxlength="4" onchange="changeIcon('${encodeURIComponent(c)}',this.value)"><span>${esc(c)} <small style="color:#8a94a6">(${use[c]||0})</small></span><button class="btn icon danger" ${use[c]?'disabled':''} onclick="deleteCat('${encodeURIComponent(c)}')">刪除</button></div>`).join('')}
window.changeIcon=async(c,v)=>{c=decodeURIComponent(c);icons[c]=(v||'📌').trim()||'📌';await saveIcons();render();autoMeta()};
window.deleteCat=async c=>{c=decodeURIComponent(c);if(records.some(r=>r.category===c))return toast('此分類仍有紀錄，無法刪除');if(!confirm(`確定刪除分類「${c}」？`))return;cats=cats.filter(x=>x!==c);delete icons[c];await saveCats();await saveIcons();catUI();render();autoMeta()};
function filtered(){let q=$('#searchInput').value.trim().toLowerCase(),c=$('#categoryFilter').value,f=$('#favoriteFilter').value,a=$('#dateFrom').value,b=$('#dateTo').value;return records.filter(r=>{let h=[r.title,r.category,r.description,r.symptom,r.environment,r.cause,r.solution,r.notes,...(r.tags||[]),...(r.links||[])].join(' ').toLowerCase();return(!q||h.includes(q))&&(!c||r.category===c)&&(!f||r.favorite)&&(!a||r.date>=a)&&(!b||r.date<=b)}).sort((a,b)=>Number(!!b.favorite)-Number(!!a.favorite)||(b.date||'').localeCompare(a.date||'')||(b.updatedAt||'').localeCompare(a.updatedAt||''))}
function render(){let rows=filtered(),now=new Date(),ym=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;$('#resultCount').textContent=`${rows.length} 筆紀錄`;$('#statTotal').textContent=records.length;$('#statFavorite').textContent=records.filter(r=>r.favorite).length;$('#statMonth').textContent=records.filter(r=>(r.date||'').startsWith(ym)).length;$('#statCategories').textContent=cats.length;catList();applyView();if(!rows.length)return $('#records').innerHTML='<div class="empty"><div class="big">🗂️</div><b>目前沒有符合的紀錄</b><div style="margin-top:6px">可以新增第一筆問題處理紀錄，或調整搜尋條件。</div></div>';$('#records').innerHTML=rows.map(r=>`<article class="card"><div class="category-icon">${esc(icon(r.category))}</div><div class="card-main"><div class="card-head"><div><h3 class="card-title">${esc(r.title)}</h3><div class="meta" style="margin-top:8px"><span class="badge">${esc(r.category)}</span>${r.environment?`<span class="badge gray">${esc(r.environment.split('\n')[0].slice(0,45))}</span>`:''}${r.attachments?.length?`<span class="badge gray">📎 ${r.attachments.length}</span>`:''}</div></div><button class="star ${r.favorite?'on':''}" onclick="toggleFav('${r.id}')">${r.favorite?'★':'☆'}</button></div><div class="desc">${esc(r.description||'')}</div>${r.tags?.length?`<div class="tags">${r.tags.slice(0,6).map(t=>`<span class="tag">#${esc(t)}</span>`).join('')}</div>`:''}</div><div class="card-foot"><span class="date">${esc(r.date||'')}</span><div class="spacer"></div><button class="btn" onclick="showDetail('${r.id}')">查看</button><button class="btn" onclick="showEdit('${r.id}')">編輯</button></div></article>`).join('')}
window.toggleFav=async id=>{let r=records.find(x=>x.id===id);if(!r)return;r.favorite=!r.favorite;r.updatedAt=new Date().toISOString();await put(RS,r);render();autoRecord(r)};
const sec=(t,c)=>c?`<div class="detail-section"><h3>${t}</h3><div class="box">${esc(c).replace(/\n/g,'<br>')}</div></div>`:'';
function detailGallery(r){let at=r.attachments||[];if(!at.length)return'';return `<div class="detail-section"><h3>附件 / 截圖</h3><div class="gallery">${at.map((a,i)=>`<div class="gallery-item"><img id="detailAtt_${i}" src="${a.data||cloudPlaceholder}" alt="${esc(a.name||'附件')}" onclick="openAttachment('${r.id}',${i})"><div class="attachment-label">${a.driveFileId?'☁️ ':''}${esc(a.name||`附件 ${i+1}`)}</div></div>`).join('')}</div></div>`}
window.showDetail=id=>{let r=records.find(x=>x.id===id);if(!r)return;detailId=id;let links=r.links||[];$('#detailBody').innerHTML=`<div class="detail-title">${esc(icon(r.category))} ${esc(r.title)}</div><div class="meta" style="margin-bottom:20px"><span class="badge">${esc(r.category)}</span><span class="badge gray">${esc(r.date)}</span>${r.favorite?'<span class="badge" style="background:#fff6dc;color:#9a6500">★ 收藏</span>':''}${r.attachments?.some(a=>a.driveFileId)?'<span class="badge" style="background:#e8f8ef;color:#18794e">☁️ Drive 附件</span>':''}</div>${sec('問題描述',r.description)}${sec('錯誤訊息 / 症狀',r.symptom)}${sec('發生環境',r.environment)}${sec('原因',r.cause)}${sec('解決方式',r.solution)}${r.tags?.length?`<div class="detail-section"><h3>關鍵字 / 標籤</h3><div class="tags">${r.tags.map(t=>`<span class="tag">#${esc(t)}</span>`).join('')}</div></div>`:''}${links.length?`<div class="detail-section"><h3>參考網址</h3><div class="box link-list">${links.map((u,i)=>`<a href="${esc(u)}" target="_blank" rel="noopener">🔗 參考連結 ${i+1}：${esc(u)}</a>`).join('')}</div></div>`:''}${sec('備註',r.notes)}${detailGallery(r)}`;modal('detailModal');hydrateRecordAttachments(r,'detail')};
function resetForm(){editId=null;attachments=[];$('#recordForm').reset();$('#editTitle').textContent='新增問題紀錄';$('#fDate').value=dateNow();$('#fCategory').value=cats[0]||'';$('#fFavorite').value='0';preview()}
window.showEdit=id=>{let r=records.find(x=>x.id===id);if(!r)return;editId=id;attachments=structuredClone(r.attachments||[]);$('#editTitle').textContent='編輯問題紀錄';[['fCategory','category'],['fDate','date'],['fTitle','title'],['fDescription','description'],['fSymptom','symptom'],['fEnvironment','environment'],['fCause','cause'],['fSolution','solution'],['fNotes','notes']].forEach(([a,b])=>$('#'+a).value=r[b]||'');$('#fLinks').value=(r.links||[]).join('\n');$('#fTags').value=(r.tags||[]).join(', ');$('#fFavorite').value=r.favorite?'1':'0';$('#fFiles').value='';preview();modal('detailModal',false);modal('editModal')};
function preview(){$('#attachPreview').innerHTML=attachments.map((a,i)=>`<div class="attach-item"><img id="editAtt_${i}" src="${a.data||cloudPlaceholder}" alt="${esc(a.name||'附件')}"><span class="cloud-mark">${a.driveFileId?'☁️':''}</span><button type="button" onclick="removeAtt(${i})">✕</button><div class="attachment-label">${esc(a.name||`附件 ${i+1}`)}</div></div>`).join('');if(editId){let r=records.find(x=>x.id===editId);if(r)hydrateEditAttachments(r)}}
window.removeAtt=i=>{attachments.splice(i,1);preview()};
async function readFiles(fs){let out=[];for(let f of fs){if(!f.type.startsWith('image/'))continue;if(out.length+attachments.length>=5){toast('附件最多 5 張');break}if(f.size>2*1024*1024){toast(`略過 ${f.name}：超過 2 MB`);continue}let data=await new Promise((ok,no)=>{let x=new FileReader;x.onload=()=>ok(x.result);x.onerror=no;x.readAsDataURL(f)});out.push({localId:uid(),name:f.name,type:f.type,size:f.size,data})}return out}
function cloudOK(){return !!(sync.url&&sync.key)}
const cleanRec=r=>{let x={...r};delete x.attachments;return x};
const attachmentPayload=list=>(list||[]).map(a=>{let x={localId:a.localId||'',name:a.name||'image',type:a.type||'image/png',size:Number(a.size||0),driveFileId:a.driveFileId||''};if(!x.driveFileId&&a.data)x.data=a.data;return x});
async function postCloud(x){if(!cloudOK())throw Error('尚未設定雲端同步');await fetch(sync.url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...x,key:sync.key})})}
function jsonp(p,timeoutMs=15000){return new Promise((ok,no)=>{if(!cloudOK())return no(Error('尚未設定雲端同步'));let cb='itkb_'+Date.now()+Math.random().toString(36).slice(2),sc=document.createElement('script');let timer=setTimeout(()=>done(Error('雲端回應逾時')),timeoutMs);let done=(e,d)=>{clearTimeout(timer);delete window[cb];sc.remove();e?no(e):ok(d)};window[cb]=d=>d?.ok===false?done(Error(d.error||'同步失敗')):done(null,d);let u=new URL(sync.url);Object.entries({...p,key:sync.key,callback:cb}).forEach(([k,v])=>u.searchParams.set(k,v));sc.onerror=()=>done(Error('無法連線 Apps Script'));sc.src=u;document.body.appendChild(sc)})}
async function refreshRecordManifest(r){let d=await jsonp({action:'record',id:r.id});if(!d.record)return;r.attachments=mergeAttachments(d.record.attachments||[],r.attachments||[]);await put(RS,r)}
async function syncRecordCloud(r){await postCloud({action:'upsert',record:cleanRec(r)});await postCloud({action:'syncAttachments',id:r.id,attachments:attachmentPayload(r.attachments)});await refreshRecordManifest(r)}
async function autoRecord(r){if(!sync.autoSync||!cloudOK())return;try{syncStatus('☁️ 同步紀錄與圖片…');await syncRecordCloud(r);render();syncStatus('☁️ 同步完成');setTimeout(()=>syncStatus(),1600)}catch(e){console.error(e);syncStatus('⚠️ 自動同步失敗')}}
async function autoDelete(id){if(sync.autoSync&&cloudOK())try{await postCloud({action:'delete',id})}catch{syncStatus('⚠️ 自動同步失敗')}}
async function autoMeta(){if(sync.autoSync&&cloudOK())try{await postCloud({action:'meta',categories:cats,categoryIcons:icons})}catch{syncStatus('⚠️ 自動同步失敗')}}
async function pushCloud(){if(!cloudOK())return alert('請先輸入 Web App 網址與同步金鑰。');let imageCount=records.reduce((n,r)=>n+(r.attachments?.length||0),0);if(!confirm(`將本機 ${records.length} 筆紀錄與 ${imageCount} 張附件同步到 Google 試算表 / Drive，並以本機紀錄清單為準，是否繼續？`))return;try{syncStatus('☁️ 上傳文字資料…');await postCloud({action:'replaceAll',records:records.map(cleanRec),categories:cats,categoryIcons:icons});for(let i=0;i<records.length;i++){syncStatus(`☁️ 同步附件 ${i+1}/${records.length}…`);await postCloud({action:'syncAttachments',id:records[i].id,attachments:attachmentPayload(records[i].attachments)})}syncStatus('☁️ 更新 Drive 附件索引…');let latest=await jsonp({action:'list'});let remoteMap=new Map((latest.records||[]).map(r=>[r.id,r]));for(let r of records){let rr=remoteMap.get(r.id);if(rr){r.attachments=mergeAttachments(rr.attachments||[],r.attachments||[]);await put(RS,r)}}render();toast('雲端資料與 Drive 附件同步完成');setTimeout(()=>syncStatus(),1800)}catch(e){alert('上傳失敗：'+e.message);syncStatus()}}
function mergeAttachments(remote=[],local=[]){let used=new Set();let out=(remote||[]).map(ra=>{let idx=local.findIndex((la,i)=>!used.has(i)&&((ra.driveFileId&&la.driveFileId===ra.driveFileId)||(ra.localId&&la.localId===ra.localId)));if(idx<0)idx=local.findIndex((la,i)=>!used.has(i)&&!la.driveFileId&&!ra.driveFileId&&la.name===ra.name&&la.type===ra.type);if(idx>=0){used.add(idx);return {...ra,data:local[idx].data||undefined,localId:ra.localId||local[idx].localId||''}}return ra});local.forEach((la,i)=>{if(!used.has(i)&&!la.driveFileId)out.push(la)});return out.slice(0,5)}
async function pullCloud(){if(!cloudOK())return alert('請先輸入 Web App 網址與同步金鑰。');try{syncStatus('☁️ 下載中…');let d=await jsonp({action:'list'}),remote=Array.isArray(d.records)?d.records:[];if(d.driveEnabled!==true){alert('雲端 Apps Script 仍是舊版，尚未啟用 Google Drive 圖片同步。請先更新 Code.gs、執行 setup() 並重新部署。');return syncStatus()}if(!confirm(`雲端共有 ${remote.length} 筆紀錄。下載後以雲端文字資料與 Drive 附件清單為準，是否繼續？`))return syncStatus();let localMap=new Map(records.map(r=>[r.id,r]));records=remote.map(r=>({...r,attachments:mergeAttachments(r.attachments||[],localMap.get(r.id)?.attachments||[])}));await clear(RS);for(let r of records)await put(RS,r);if(d.categories?.length){cats=d.categories;await saveCats()}if(d.categoryIcons){icons={...ICONS,...d.categoryIcons};await saveIcons()}catUI();render();toast('已從雲端下載文字資料與 Drive 附件清單');syncStatus()}catch(e){alert('下載失敗：'+e.message);syncStatus()}}
async function fetchAttachmentData(a){if(a.data)return a.data;if(!a.driveFileId)throw Error('此附件尚未同步到 Drive');let d=await jsonp({action:'attachment',fileId:a.driveFileId},30000);if(!d.data)throw Error('Drive 未回傳圖片內容');a.data=d.data;a.type=d.type||a.type;a.size=d.size||a.size;a.name=d.name||a.name;return a.data}
async function hydrateRecordAttachments(r,prefix){let list=r.attachments||[],changed=false;for(let i=0;i<list.length;i++){let a=list[i];if(a.data||!a.driveFileId)continue;try{let data=await fetchAttachmentData(a);changed=true;let img=document.getElementById(`${prefix}Att_${i}`);if(img)img.src=data}catch(e){console.warn(e);let img=document.getElementById(`${prefix}Att_${i}`);if(img){img.alt='Drive 圖片載入失敗';img.title=e.message}}}if(changed)await put(RS,r)}
async function hydrateEditAttachments(r){let changed=false;for(let i=0;i<attachments.length;i++){let a=attachments[i];if(a.data||!a.driveFileId)continue;try{let data=await fetchAttachmentData(a);changed=true;let img=document.getElementById(`editAtt_${i}`);if(img)img.src=data}catch(e){console.warn(e)}}if(changed){r.attachments=structuredClone(attachments);await put(RS,r)}}
window.openAttachment=async(id,i)=>{let r=records.find(x=>x.id===id),a=r?.attachments?.[i];if(!a)return;try{let data=await fetchAttachmentData(a);await put(RS,r);window.open(data,'_blank')}catch(e){alert('圖片載入失敗：'+e.message)}};
$('#recordForm').addEventListener('submit',async e=>{e.preventDefault();let now=new Date().toISOString(),old=editId?records.find(x=>x.id===editId):null;let r={id:editId||uid(),category:$('#fCategory').value,date:$('#fDate').value,title:$('#fTitle').value.trim(),description:$('#fDescription').value.trim(),symptom:$('#fSymptom').value.trim(),environment:$('#fEnvironment').value.trim(),cause:$('#fCause').value.trim(),solution:$('#fSolution').value.trim(),links:$('#fLinks').value.split(/\n+/).map(x=>x.trim()).filter(Boolean),tags:$('#fTags').value.split(/[,，\n]+/).map(x=>x.trim()).filter(Boolean),favorite:$('#fFavorite').value==='1',notes:$('#fNotes').value.trim(),attachments,createdAt:old?.createdAt||now,updatedAt:now};await put(RS,r);let i=records.findIndex(x=>x.id===r.id);i>=0?records[i]=r:records.push(r);let was=!!editId;modal('editModal',false);render();toast(was?'紀錄已更新':'紀錄已新增');autoRecord(r);resetForm()});
$('#fFiles').addEventListener('change',async e=>{attachments.push(...await readFiles([...e.target.files]));preview();e.target.value=''});
$('#btnAdd').onclick=()=>{resetForm();modal('editModal')};
$('#detailEdit').onclick=()=>detailId&&showEdit(detailId);
$('#detailDelete').onclick=async()=>{if(!detailId)return;let r=records.find(x=>x.id===detailId);if(!confirm(`確定刪除「${r?.title||'這筆紀錄'}」？雲端同步開啟時，對應 Drive 附件也會移至垃圾桶。`))return;await del(RS,detailId);records=records.filter(x=>x.id!==detailId);modal('detailModal',false);render();autoDelete(detailId);toast('紀錄已刪除')};
$('#btnCategories').onclick=()=>modal('categoryModal');
$('#addCategory').onclick=async()=>{let c=$('#newCategory').value.trim();if(!c)return;if(cats.some(x=>x.toLowerCase()===c.toLowerCase()))return toast('分類已存在');cats.push(c);icons[c]=$('#newCategoryIcon').value.trim()||'📌';$('#newCategory').value='';$('#newCategoryIcon').value='📌';await saveCats();await saveIcons();catUI();autoMeta();toast('分類已新增')};
['searchInput','categoryFilter','favoriteFilter','dateFrom','dateTo'].forEach(id=>$('#'+id).addEventListener(id==='searchInput'?'input':'change',render));
$('#btnClearFilters').onclick=()=>{$('#searchInput').value='';$('#categoryFilter').value='';$('#favoriteFilter').value='';$('#dateFrom').value='';$('#dateTo').value='';render()};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>modal(b.dataset.close,false));
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>e.target===m&&modal(m.id,false)));
document.addEventListener('keydown',e=>e.key==='Escape'&&document.querySelectorAll('.modal.show').forEach(m=>modal(m.id,false)));
$('#viewCards').onclick=()=>{view='cards';localStorage.setItem('itkb_viewMode',view);applyView()};
$('#viewList').onclick=()=>{view='list';localStorage.setItem('itkb_viewMode',view);applyView()};
$('#btnSync').onclick=()=>{$('#syncUrl').value=sync.url||'';$('#syncKey').value=sync.key||'';$('#syncAuto').checked=!!sync.autoSync;modal('syncModal');if(cloudOK())jsonp({action:'ping'}).then(d=>{let el=$('#syncDriveState');if(el)el.textContent=d.driveEnabled?'✅ Drive 圖片同步後端已啟用':'⚠️ 後端仍為舊版'}).catch(()=>{let el=$('#syncDriveState');if(el)el.textContent='⚠️ 無法確認 Drive 後端狀態'})};
async function readSyncForm(){sync={url:$('#syncUrl').value.trim(),key:$('#syncKey').value.trim(),autoSync:$('#syncAuto').checked};await saveSync();syncStatus()}
$('#btnSaveSync').onclick=async()=>{await readSyncForm();modal('syncModal',false);toast('雲端同步設定已儲存')};
$('#btnPushCloud').onclick=async()=>{await readSyncForm();pushCloud()};
$('#btnPullCloud').onclick=async()=>{await readSyncForm();pullCloud()};
$('#btnExport').onclick=()=>{let b=new Blob([JSON.stringify({app:'IT 問題處理知識庫',version:3,exportedAt:new Date().toISOString(),categories:cats,categoryIcons:icons,records},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`IT知識庫備份_${dateNow().replaceAll('-','')}.json`;a.click();URL.revokeObjectURL(a.href);toast('備份檔已匯出')};
$('#btnImport').onclick=()=>$('#importFile').click();
$('#importFile').onchange=async e=>{let f=e.target.files[0];e.target.value='';if(!f)return;try{let d=JSON.parse(await f.text());if(!Array.isArray(d.records))throw 0;if(!confirm(`將匯入 ${d.records.length} 筆紀錄，ID 相同會覆蓋，是否繼續？`))return;for(let r of d.records)await put(RS,r);if(d.categories?.length){cats=[...new Set([...cats,...d.categories])];await saveCats()}if(d.categoryIcons){icons={...ICONS,...d.categoryIcons};await saveIcons()}await load();toast('備份匯入完成')}catch{alert('匯入失敗：不是有效的知識庫備份檔。')}};
(async()=>{try{await openDB();await load();resetForm()}catch(e){console.error(e);alert('無法開啟瀏覽器資料庫。請確認瀏覽器允許網站儲存資料。')}})();